### ISSUE TITLE
[import-report] Connector failing to import PDF reports

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/connectors#483] opened 2021-09-21 22:21 UTC
## Description

When trying to import reports, the task fails with the error:

ERROR:root:Error in message processing, reporting error to API"
Traceback (most recent call last):
  File ""/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py"", line 152, in _data_handler"
    message = self.callback(json_data[""event""])"
  File ""/opt/opencti-connector-import-report/reportimporter/core.py"", line 68, in _process_message"
    entity_indicators = self._collect_stix_objects(self.entity_config)
  File ""/opt/opencti-connector-import-report/reportimporter/core.py"", line 121, in _collect_stix_objects"
    entity_list += entity_config.convert_to_entity(entries)
  File ""/opt/opencti-connector-import-report/reportimporter/models.py"", line 150, in convert_to_entity"
    regex = re.compile(indicators, re.IGNORECASE)"
  File ""/usr/local/lib/python3.9/re.py"", line 252, in compile"
    return _compile(pattern, flags)"
  File ""/usr/local/lib/python3.9/re.py"", line 304, in _compile"
    p = sre_compile.compile(pattern, flags)"
  File ""/usr/local/lib/python3.9/sre_compile.py"", line 764, in compile"
    p = sre_parse.parse(p, flags)"
  File ""/usr/local/lib/python3.9/sre_parse.py"", line 948, in parse"
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)"
  File ""/usr/local/lib/python3.9/sre_parse.py"", line 443, in _parse_sub"
    itemsappend(_parse(source, state, verbose, nested + 1,"
  File ""/usr/local/lib/python3.9/sre_parse.py"", line 671, in _parse"
    raise source.error(""multiple repeat"","
re.error: multiple repeat at position 40
INFO:root:Reporting work update_received opencti-work--eab72fb2-5905-4a2d-805a-7453a7a37491
INFO:root:Message (delivery_tag=2) processed, thread terminated"

## Environment

1. OS (where OpenCTI server runs): AWS ECS Fargate
2. OpenCTI version: 4.5.5
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Attempt to import a report
2. Wait for task to fail
3. Open issue on GitHub

## Expected Output

Report imported and indicators extracted

## Actual Output

Job fails

**Comment by sorenopsy** [comment] 2021-09-22 06:47
Same with version 5.0.0 on docker:
DEBUG:pika.adapters.utils.io_services_utils:Recv would block on <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.17', 52616), raddr=('172.18.0.4', 5672)>
INFO:root:Reporting work update_received opencti-work--c02d58c8-26ee-4cdf-9121-66c0de54200b
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc2820> with deadline=7692706.591058159 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36b1da7c0>>; now=7692705.591058159; delay=1.0
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 90
INFO:root:Importing the file http://opencti:8080/storage/get/import/Report/c6c3012b-dc79-493a-8246-c75a953eb0b2/ioc_test.pdf
DEBUG:urllib3.connectionpool:http://opencti:8080 "GET /storage/get/import/Report/c6c3012b-dc79-493a-8246-c75a953eb0b2/ioc_test.pdf HTTP/1.1" 200 None
INFO:root:Listing Campaigns with filters null.
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Identities with filters null.
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Incidents with filters null.
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Intrusion-Sets with filters null.
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc2190> with deadline=7692707.593762935 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36b1f2b00>>; now=7692706.593762935; delay=1.0
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc27c0> with deadline=7692708.596314715 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36b1f2b00>>; now=7692707.596314715; delay=1.0
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Locations with filters {"key": "entity_type", "values": ["Country"]}.
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc27f0> with deadline=7692709.59732178 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36ac04fc0>>; now=7692708.59732178; delay=1.0
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
INFO:root:Listing Malwares with filters null.
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc2490> with deadline=7692710.598318689 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36ae66bc0>>; now=7692709.598318689; delay=1.0
DEBUG:pika.heartbeat:Sending heartbeat frame
DEBUG:pika.heartbeat:Sending heartbeat frame
DEBUG:pika.adapters.utils.selector_ioloop_adapter:SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncPlaintextTransport._on_socket_writable of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa36bc9d5b0>>)
DEBUG:pika.adapters.utils.selector_ioloop_adapter:set_writer(7, _) updated handler RdWr
DEBUG:pika.adapters.utils.io_services_utils:Turned on writability watcher: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.17', 52616), raddr=('172.18.0.4', 5672)>
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36afa5340> with deadline=7692740.019816316 and callback=<bound method HeartbeatChecker._send_heartbeat of <pika.heartbeat.HeartbeatChecker object at 0x7fa36be218e0>>; now=7692710.019816316; delay=30.0
DEBUG:pika.adapters.utils.selector_ioloop_adapter:SelectorIOServicesAdapter.remove_writer(7)
DEBUG:pika.adapters.utils.selector_ioloop_adapter:remove_writer(7) updated handler Rd
DEBUG:pika.adapters.utils.io_services_utils:Turned off writability watcher: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.17', 52616), raddr=('172.18.0.4', 5672)>
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 None
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 154, in _data_handler
    message = self.callback(json_data["event"])
  File "/opt/opencti-connector-import-report/reportimporter/core.py", line 69, in _process_message
    entity_indicators = self._collect_stix_objects(self.entity_config)
  File "/opt/opencti-connector-import-report/reportimporter/core.py", line 125, in _collect_stix_objects
    entity_list += entity_config.convert_to_entity(entries, self.helper)
  File "/opt/opencti-connector-import-report/reportimporter/models.py", line 150, in convert_to_entity
    indicators.append(re.compile(value, re.IGNORECASE))
  File "/usr/local/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.9/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 4
INFO:root:Reporting work update_received opencti-work--c02d58c8-26ee-4cdf-9121-66c0de54200b
DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x7fa36bfc2340> with deadline=7692711.608398806 and callback=<bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa36b122cc0>>; now=7692710.608398806; delay=1.0
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 91
DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 98
INFO:root:Message (delivery_tag=2) processed, thread terminated
DEBUG:pika.adapters.utils.selector_ioloop_adapter:SelectorIOServicesAdapter.set_writer(7, <bound method _AsyncPlaintextTransport._on_socket_writable of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa36bc9d5b0>>)
DEBUG:pika.adapters.utils.selector_ioloop_adapter:set_writer(7, _) updated handler RdWr
DEBUG:pika.adapters.utils.io_services_utils:Turned on writability watcher: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.17', 52616), raddr=('172.18.0.4', 5672)>
DEBUG:pika.adapters.utils.selector_ioloop_adapter:SelectorIOServicesAdapter.remove_writer(7)
DEBUG:pika.adapters.utils.selector_ioloop_adapter:remove_writer(7) updated handler Rd
DEBUG:pika.adapters.utils.io_services_utils:Turned off writability watcher: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.17', 52616), raddr=('172.18.0.4', 5672)>

**Comment by nor3th** [comment] 2021-09-23 19:39
Hey @TechBurn0ut and @sorenopsy 

Thanks for reporting this issue. I just added some improved logging for this issue since I can't reproduce it myself. Please use the `rolling` docker version, try importing your report again and please post the error log the connector should throw now if there's some issue with the regex.  https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-report/src/reportimporter/models.py#L150-L155

Regards,

**Comment by nor3th** [comment] 2021-10-01 12:29
Closing this for now as this has been fixed. If this issue appears again, please open this issue again.

**Closed by nor3th** 2021-10-01 12:29 UTC
Labels: bug
