### ISSUE TITLE
 When running alienvault connector alone, an error is encountered

### ISSUE THREAD

**Issue by 15271843622** [OpenCTI-Platform/connectors#160] opened 2020-06-03 03:51 UTC
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Opencti platform is running normally. When running alienvault connector alone, an error is encountered. The following is the configuration screenshot and error report

## Environment

1. OS (where OpenCTI server runs): {  Ubuntu 19.10 }
2. OpenCTI version: { e.g. OpenCTI 3.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducibl
![main error](https://user-images.githubusercontent.com/41221477/83593912-711fbb00-a590-11ea-9b9f-c6686d3b5627.png)
![error](https://user-images.githubusercontent.com/41221477/83593913-711fbb00-a590-11ea-86dc-1bbbd8a9b7e4.png)

e scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by maertv** [comment] 2020-06-03 06:44
@15271843622, please attach the exact configuration file (i.e., _config.yml_, remove your credentials beforehand) which causes this error.

Based on the picture is hard to say what is wrong because the error suggests that the _alienvault.report_status_ configuration parameter is missing from the file which does not seem to be the case. Also make sure that the environment variable _ALIENVAULT_REPORT_STATUS_  is not set.

I tried reproducing the error by making a copy of _config.yml.sample_ and modifying the file to match the picture but I couldn't get the error.

**Comment by 15271843622** [comment] 2020-06-03 07:27
After the restart, the problem has been solved. Thank you

**Comment by maertv** [comment] 2020-06-03 07:43
> After the restart, the problem has been solved. Thank you

You're welcome.

Closing the issue.

**Closed by maertv** 2020-06-03 07:43 UTC
