### ISSUE TITLE
[TheHive] Unable to sync cases from theHive to OpenCTI

### ISSUE THREAD

**Issue by sho-illuminate** [OpenCTI-Platform/connectors#326] opened 2021-04-14 12:28 UTC
## Description

I am trying to sync theHive's cases to openCTI using opencti - theHive connector.

## Environment

Question | Answer
-- | --
OS version (host) | Windows 10
OS version (guests) | CentOS 7.8
TheHive version | 4.0.5-1
Package Type | Docker
TheHive4py | 1.8.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start theHive with docker and openCTI + openCTI - theHive connector using docker.
2. create test cases in theHive UI and wait for sync.

## Expected Output

See theHive cases when accessing openCTI's UI.

## Actual Output

Nothing is importing over from theHive. I created 3 test cases.
 
## Additional information

I also recently submitted two issues to theHive team that provide more information about the issue. 

https://github.com/TheHive-Project/TheHive4py/issues/217 
https://github.com/TheHive-Project/TheHive/issues/1958

**Comment by SamuelHassine** [comment] 2021-04-18 10:17
Hello,

The connector has been tested with TheHive 3 latest version but not TheHive 4. We will re-work the integration to make this compatible asap.

**Comment by SamuelHassine** [comment] 2021-04-29 09:27
Duplicate of #347.

**Closed by SamuelHassine** 2021-04-29 09:27 UTC
