### ISSUE TITLE
cybercrime-tracker 

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/connectors#235] opened 2021-02-04 17:52 UTC
Same issue in cybercrime-tracker connector .. "Failure in name resolution"

![image](https://user-images.githubusercontent.com/20463433/106934252-e62b2d80-66e7-11eb-9bc4-7156189b2569.png)

**Comment by SamuelHassine** [comment] 2021-02-05 11:20
Hello @NetEyes,

If you run the connector manually, you have to ensure that the connector will be able to access to the RabbitMQ server using the parameters given by the API. So lets say your platform is configured with default parameters such as:

```
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
```

If you launch your connector manually, the connector will ask to the API the RabbitMQ hostname (here it's `rabbitmq`) and then try to connect it. The error you have means that the connector is not able to resolve this hostname. 

If you want to use a setup with the platform in Docker and the connectors launched manually, you have to change your docker-compose.yml file to expose RabbitMQ Port (5672) to your Docker host/hypervisor and use the hostname of the host in your configuration.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment] 2021-02-05 11:21
Duplicate of #233.

**Closed by SamuelHassine** 2021-02-05 11:21 UTC
Labels: duplicate, question
