### ISSUE TITLE
Malpedia connector is throwing validation errors

### ISSUE THREAD

**Issue by rlynch-ironnet** [OpenCTI-Platform/connectors#1122] opened 2023-05-02 17:12 UTC
## Description

```
LogGroup: /aws/ecs/connectors/malpedia
Event: {
  "timestamp": "2023-05-02T16:59:44.113119Z",
  "level": "ERROR",
  "name": "pycti.connector",
  "message": "
error marshaling actor data for APT 29: 3 validation errors for Actor
value field required (type=value_error.missing)
meta field  required (type=value_error.missing)
uuid field required (type=value_error.missing)"
}
```

## Environment

1. OS (where OpenCTI server runs): AWS fargate
2. OpenCTI version: 5.7.3
3. OpenCTI client: Python connector
4. Other environment details: n/a

## Reproducible Steps

Run the connector?

## Expected Output

Connector doesnt throw stacktrace

## Actual Output

Got a stacktrace

## Additional information

n/a

**Comment by fwuest** [comment] 2023-05-12 10:23
We have the same issue on the following Environment:

### Environment

OS (where OpenCTI server runs): Azure Kubernetes
OpenCTI version: 5.7.4
OpenCTI client: Python connector
Other environment details: n/a

**Comment by SamuelHassine** [comment] 2024-01-16 01:01
Duplicate of #406.

**Closed by SamuelHassine** 2024-01-16 01:01 UTC
Labels: bug
