### ISSUE TITLE
[cyber-campaign-collection] Does not seem to honor the proxy settings in env

### ISSUE THREAD

**Issue by trocade** [OpenCTI-Platform/connectors#864] opened 2022-10-06 07:38 UTC
## Description

The connector is configured with the proxy in docker environment variables:
      - HTTP_PROXY=http://proxy:8080
      - HTTPS_PROXY=http://proxy:8080
      - NO_PROXY="localhost,domain,0,1,2,3,4,5,6,7,8,9"

But the connector does not seem to honor this setting:
INFO:root:Initiate work for UUID
ERROR:root:HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CyberMonitor/APT_CyberCriminal_Campagin_Collections (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff2e11c72b0>, 'Connection to api.github.com timed out. (connect timeout=15)'))
INFO:root:Connector has never run
INFO:root:Connector will run!

## Environment

1. OS (where OpenCTI server runs): Official docker images
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } Opencti 5.3.16
3. OpenCTI client: { e.g. frontend or python } 
4. Other environment details:
All other connectors use this proxy config without any problems.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure connector to use proxy in environment
2. Run connector
3. Unable to connect

## Expected Output

The connector to use the proxy to connect to api.github.com

## Actual Output

ERROR:root:HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/CyberMonitor/APT_CyberCriminal_Campagin_Collections (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff2e11c72b0>, 'Connection to api.github.com timed out. (connect timeout=15)'))

**Comment by 0xalpaca** [comment] 2022-10-27 07:28
I've got the same kind of problem. On my side, it's related to AlienVault.

Error:
```
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 46f004c5-dff1-42de-9e3c-6456e48ef326
INFO:root:Starting ping alive thread
INFO:root:Starting AlienVault connector...
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {}
INFO:root:Connector first run
INFO:root:Initiate work for 46f004c5-dff1-42de-9e3c-6456e48ef326
INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False, relationships: True, patterns_indicates: True, filter_indicators: True)...
INFO:root:Fetching subscribed pulses...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 178, in get
    response = self.session().get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 8, in <module>
    connector.run()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 255, in run
    pulse_import_state = self.pulse_importer.run(current_state, work_id)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 100, in run
    pulses = self._fetch_subscribed_pulses(latest_pulse_datetime)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 191, in _fetch_subscribed_pulses
    pulses = self.client.get_pulses_subscribed(modified_since)
  File "/opt/opencti-connector-alienvault/alienvault/client.py", line 40, in get_pulses_subscribed
    pulse_data = self.otx.getsince(timestamp=modified_since, limit=limit)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 431, in getsince
    return self.getall(limit=limit, modified_since=timestamp, max_page=max_page, max_items=max_items, iter=False)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 404, in getall
    return self.walkapi(
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 385, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page, max_items=max_items, method=method, body=body))
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 366, in walkapi_iter
    data = self.get(next_page_url)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 187, in get
    raise RetryError()
OTXv2.RetryError: 'Exceeded maximum number of retries'
Killed
```

In addition, I've checked with Tcpdump to see if the connection was well established at the proxy and that's the case.

At this time, I don't have any data from AlienVault.

**Comment by SAIKATDASGITHUB** [comment] 2023-08-10 08:53
Hi @Jipegien 

Is it resolved? I am getting the same error for otx.alienvault.com while adding the connector in the docker compose file.

"urllib3.connectionpool", "message": "Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd75c868950>, 'Connection to otx.alienvault.com timed out. (connect timeout=None)')': /api/v1/pulses/subscribed?limit=20&modified_since=2023-08-01T00%3A00%3A00"}

**Comment by annoyingapt** [comment] 2023-08-15 03:37
Does anyone still use this? I think the project has been abandoned.

**Comment by SamuelHassine** [comment] 2024-01-16 01:04
@Megafredo @helene-nguyen Can you please take a look?

**Comment by Megafredo** [comment] 2024-02-23 11:15
Hello, as the issue is quite old, I am currently on OpenCTI version 5.12.32.

My tests : 
- Local test of the cyber-campaign-collection connector without proxy (no problems encountered)
- Local test of the cyber-campaign-collection connector with proxy (no problems encountered, see process)
  
Procedure for setting up a proxy with docker : 
- Prerequisites: docker, opencti
- Copy the tinyproxy.conf file to your desktop (https://github.com/tinyproxy/tinyproxy/blob/master/etc/tinyproxy.conf.in)
- Comment out lines 200 to 201 "Allow 127.0.0.1" and "Allow ::1".

- Type these commands:
`docker run -d -p 8888:8888 -v tinyproxy:/etc/tinyproxy --name tinyproxy kalaksi/tinyproxy`
`docker cp tinyproxy.conf tinyproxy:/etc/tinyproxy/tinyproxy.conf`
`docker restart tinyproxy`

- Check that your container is in place:
`docker ps`
![image](https://github.com/OpenCTI-Platform/connectors/assets/14902945/2890ddbc-f143-4cd3-9e7d-e4c7a2b2bd69)

- Export the following environment variables to git bash or another Linux command line:
`export HTTP_PROXY=http://localhost:8888`
`export HTTPS_PROXY=http://localhost:8888` 
`export http_proxy=http://localhost:8888` 
`export https_proxy=http://localhost:8888` 
`export NO_PROXY=localhost`

- Before launching the connector, run this command in parallel to check that you are using the proxy:
`docker logs -f tinyproxy`

- Once finalized, run your connector with python
`python <YOURPATH>\connectors\external-import\cyber-campaign-collection\src\cyber-campaign-collection.py`

- Example of return for the 2024 collection
![image](https://github.com/OpenCTI-Platform/connectors/assets/14902945/cff64839-edc7-4197-8364-73bfcf94af01)

- In the docker logs, you should find this kind of information:
![image](https://github.com/OpenCTI-Platform/connectors/assets/14902945/0bcd86e0-771a-4b21-98d1-fe928a7a583b)

At this point, I think you need to check your proxy and its settings.

**Comment by Megafredo** [comment] 2024-02-28 06:54
I will close the issue, we can reopen it if necessary or if you need more details.

**Closed by Megafredo** 2024-02-28 06:54 UTC
Labels: bug, filigran team

**Comment by SAIKATDASGITHUB** [comment] 2024-02-28 06:58
Hi @Megafredo,

Please close this as we have resolved  it. The issue was related to proxy in our internal server. We have installed it in Cloud and it is working.
