### ISSUE TITLE
Vurustotal issues to elements : field': 'externalReferences

### ISSUE THREAD

**Issue by sebascorrea** [OpenCTI-Platform/connectors#2205] opened 2024-06-10 01:03 UTC
Virus total and other connectors have issues when try to create elements: "{'name': 'VALIDATION_ERROR', 'error_message': 'Validation error', 'http_status': 500, 'genre': 'BUSINESS', 'field': 'externalReferences', 'message': 'This attribute is mandatory', 'attribute': 'externalReferences'}"

I have the opencti/platform:6.1.10

<img width="1419" alt="image" src="https://github.com/OpenCTI-Platform/docker/assets/68032961/94ff261b-0771-476d-af14-4a68dce05fc8">

<img width="1419" alt="image" src="https://github.com/OpenCTI-Platform/docker/assets/68032961/50194b26-c0b9-44e5-88cd-aee9435cf820">

**Comment by romain-filigran** [comment] 2024-06-10 07:42
Hello. Unable to reproduce on my side. 
Does your connectors version are well aligned with platform version ? In your case 6.1.10 ?

**Comment by sebascorrea** [comment] 2024-06-11 03:32
> Hello. Unable to reproduce on my side. Does your connectors version are well aligned with platform version ? In your case 6.1.10 ?

  connector-virustotal:
    image: opencti/connector-virustotal:6.1.10
    environment:
      - OPENCTI_URL=http://opencti:8080

Yes, the same version

**Comment by sebascorrea** [comment] 2024-06-12 22:55
142.202.48.115 for example

**Comment by Jipegien** [comment] 2024-06-14 07:20
Is the enforce reference config checked in some of your Entity type in Customization?
![image](https://github.com/OpenCTI-Platform/connectors/assets/104078945/df9f8038-5c03-4c2e-b22b-fa71385022d3)

**Comment by nino-filigran** [comment] 2024-08-19 07:36
Closing this ticket for now since no activity on it. Feel free to re-open it if needed.

**Closed by nino-filigran** 2024-08-19 07:36 UTC
Labels: bug, needs more info
