### ISSUE TITLE
How to connect SIEM QRADAR with OPENCTI as a stream connector?

### ISSUE THREAD

**Issue by HabibaAkram-KICS** [OpenCTI-Platform/connectors#912] opened 2022-11-15 06:15 UTC
Hi, I do not find opensource siem connector for opencti. Kindly guide how can we connect siem with opencti(installed via docker).

**Comment by SamuelHassine** [comment] 2022-11-17 00:39
Duplicate of #513.

**Closed** 2022-11-17 00:39 UTC
Labels: duplicate, feature
